// TYPES
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGIN_MANAGER = "LOGIN_MANAGER";
export const LOGOUT_MANAGER = "LOGOUT_MANAGER";
export const AUTHENTICATE_MANAGER = "AUTHENTICATE_MANAGER";
export const UPDATE_USER = "UPDATE_USER";
